### PR TITLE
nightly build

### PR DESCRIPTION
**Pull request by LukasBoll**
nightly build at 23:00 UTC

### CODE REVIEW

**Comment by JonasHelming** [comment]
#102

**Review by JonasHelming — DISMISSED** [review]

**Review by JonasHelming — CHANGES_REQUESTED** [review]
Could you check why the build fails? Does it run locally?

**Comment by vince-fugnitto** [comment]
> Could you check why the build fails? Does it run locally?

@JonasHelming it fails locally when I attempt to generate the `tree-editor` template:
- `git checkout master`
- `git init`
- `npm link`
- `mkdir ~/Desktop/a`
- `cd ~/Desktop/a`
- `yo theia-extension` - select `TreeEditor`

**Comment by JonasHelming** [comment]
This very clearly shows the need for having a nightly, the template is indeed broken with the lates Theia version: https://github.com/eclipse-theia/generator-theia-extension/issues/105

**Comment by JonasHelming** [comment]
OK, the tree editor should be fixed, @LukasBoll could you rebase on master please?

**Comment by LukasBoll** [comment]
> OK, the tree editor should be fixed, @LukasBoll could you rebase on master please?

Yes, I just rebased.

**Review by vince-fugnitto — APPROVED** [review]

**Review by JonasHelming — APPROVED** [review]

**Pull request merged**
