### PR TITLE
Added electron as dev dependency

### LINKED ISSUE #127: Electron builds in generated templates are broken with Theia version 1.22
This is very likely due to the Electron Upgrade of Theia, we need to adapt the templates to this.
As a temporary work around, you can generate with: 
`--theiaVersion 1.21`
(the last working version)

### PR DESCRIPTION
**Pull request by JonasHelming**
fixed #127

### CODE REVIEW

**Comment by JonasHelming** [comment]
@vince-fugnitto : If this works for you, we should release

**Review by vince-fugnitto — APPROVED** [review]
I confirmed that I am able to successfully start the electron app with the changes :+1: 

image

**Comment by JonasHelming** [comment]
@vince-fugnitto : Can we trigger a release?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto : Can we trigger a release?

The release should be published now https://github.com/eclipse-theia/generator-theia-extension/releases/tag/v0.1.28 :+1: 


```bash
$ npm info generator-theia-extension

generator-theia-extension@0.1.28 | EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 | deps: 1 | versions: 28
Helps to setup the project structure for developing extensions to the Theia IDE
https://github.com/theia-ide/generator-theia-extension

keywords: yeoman-generator

dist
.tarball: https://registry.npmjs.org/generator-theia-extension/-/generator-theia-extension-0.1.28.tgz
.shasum: 0996b4c62626418dc0454b26fa64fee4814385d9
.integrity: sha512-YzCTRtBDSYXQlFwgu79tVJtGz9plOcZ/3CvZn6c0Kb8g7lFrZwHitKFMD5OSJi0qJULmKTuilpXfoVKgATGKLA==
.unpackedSize: 133.9 kB

dependencies:
yeoman-generator: ^4.0.2 

maintainers:
- paul-marechal <paul.marechal.0@gmail.com>
- bhufmann <Bernd.hufmann@ericsson.com>
- vince-fugnitto <vincent.fugnitto@ericsson.com>
- eclipsetheia <theia@typefox.io>

dist-tags:
latest: 0.1.28  

published a minute ago by vince-fugnitto <vincent.fugnitto@ericsson.com>
```

**Pull request merged**
