### PR TITLE
Extension default name is the extension type

### LINKED ISSUE #133: Use extension type as the extension default name
Using the parent directory a a default extension name almost never makes sense, the type seems like a better fit.

### PR DESCRIPTION
**Pull request by JonasHelming**
fixed #133

Signed-off-by: Jonas Helming <jhelming@eclipsesource.com>

### CODE REVIEW

**Comment by JonasHelming** [comment]
@vince-fugnitto : Maybe we take this one in as well and do a release?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto : Maybe we take this one in as well and do a release?

@JonasHelming I'm not sure either commit would warrant a release, they are more nice to haves than issues.

**Review by vince-fugnitto — APPROVED** [review]

**Comment by JonasHelming** [comment]
@vince-fugnitto  There are two additional fixes merged since the last release:
https://github.com/eclipse-theia/generator-theia-extension/pull/146
https://github.com/eclipse-theia/generator-theia-extension/pull/150

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto There are two additional fixes merged since the last release:
> #146
> #150

Only one is a fix although quite minor but I’ll do a release regardless if it’s what you want.

**Comment by vince-fugnitto** [comment]
@JonasHelming did you not want to merge this pull-request so we can perform the release?

**Pull request merged**
