### PR TITLE
Add 'next' theia version to nightly build

### LINKED ISSUE #116: Establish a nightly build against Theia latest main branch
We recently discussed process improvements to better support adopters to upgrade to new Theia versions. One thing we decided on is to discovered potential breaks as early as possible so that we can either avoid them or update the migration guide. As the extension generator adopts Theia, we discussed the idea of having a nightly build of it against the latest state of Theia (main branch). It would discover, whether the generated templates still builds and the basic tests still run. If this build fails, an issue should be reported back to Theia, so we must establish a process to watch the build

### PR DESCRIPTION
**Pull request by max-elia**
- Add job to build all examples with next theia version
- Softly fail and give feedback over which ones failed at the end
Fixes #116 

Signed-off-by: Max Elia Schweigkofler <max_elia@hotmail.de>

### CODE REVIEW

**Review by JonasHelming — APPROVED** [review]

**Comment by JonasHelming** [comment]
@vince-fugnitto : are you fine with this?

**Review by JonasHelming — APPROVED** [review]
We might want to add email notifcations on this

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto : are you fine with this?

@JonasHelming we might want to add a commit to fix the tree-editor so our baseline when merging is clean (actually passes CI). In the future we might consider breaking down the generation and build of all templates so we can have better traceability in the gh action itself, so we can more clearly see what is failing. Something like we did in `theia-apps`:

image

**Comment by JonasHelming** [comment]
> > @vince-fugnitto : are you fine with this?
> 
> @JonasHelming we might want to add a commit to fix the tree-editor so our baseline when merging is clean (actually passes CI). In the future we might consider breaking down the generation and build of all templates so we can have better traceability in the gh action itself, so we can more clearly see what is failing. Something like we did in `theia-apps`:
> 
> image

I agree, I opened #124. For splitting the build: Would look nicer, but we cannot loop over the templates as easy as we do now from within a GitHub action I guess...

**Comment by JonasHelming** [comment]
@vince-fugnitto : I would merge this now, template all work now

**Pull request merged**
