### PR TITLE
Add watch script to watch all packages at once

### PR DESCRIPTION
**Pull request by planger**
I often find myself adding that in Theia-based projects, especially for those that have multiple extensions.

### CODE REVIEW

**Review by vince-fugnitto — COMMENTED** [review]
Thank you for the contribution!
Do you believe `watch` should be documented, especially for new developers who are likely to use the generator, or build their own extensions for the first time? @JonasHelming any thoughts?

**Comment by JonasHelming** [comment]
Yes, I guess we should add it here as a second option alternativly to watching both separatly https://github.com/eclipse-theia/generator-theia-extension/blob/master/templates/README.md#developing-with-the-browser-example

**Comment by planger** [comment]
Thanks for the feedback! Good idea with adding the global `yarn watch` to the README, I made a suggestion in a new commit 0657143 in this PR.

**Review by vince-fugnitto — APPROVED** [review]
The changes look good thank you! Can you please squash so we can merge?

I'm a little confused as to why the docs describe the `watch` workflow in such a way where we need to launch the backends with vscode, we can alternatively also describe how to do so simply with the terminal.

**Comment by planger** [comment]
Thanks a lot! I force-pushed a single commit with all changes.

> I'm a little confused as to why the docs describe the watch workflow in such a way where we need to launch the backends with vscode, we can alternatively also describe how to do so simply with the terminal.

I agree that it would make sense to at least also mention that the backend can be started from within VSCode via the launch config or with e.g. `cd browser-app; yarn start`. Do you want me to open a separate PR with a proposal?

**Comment by vince-fugnitto** [comment]
> Thanks a lot! I force-pushed a single commit with all changes.
> 
> > I'm a little confused as to why the docs describe the watch workflow in such a way where we need to launch the backends with vscode, we can alternatively also describe how to do so simply with the terminal.
> 
> I agree that it would make sense to at least also mention that the backend can be started from within VSCode via the launch config or with e.g. `cd browser-app; yarn start`. Do you want me to open a separate PR with a proposal?

If you'd like to and agree it adds value for extension developers then please feel free to open the PR :)

**Comment by JonasHelming** [comment]
I created a ticket for the follow up so we can merge this for now

**Pull request merged**
