### PR TITLE
fix labelProvider template

### PR DESCRIPTION
**Pull request by kobzarvs**

### CODE REVIEW

**Review by vince-fugnitto — CHANGES_REQUESTED** [review]
Thank you for your first contribution @kobzarvs :+1: 

A couple of things to note:
- please add some details in the commit message, and the pull-request description as to why the changes are necessary.
- the repository is in the process of [moving](https://github.com/theia-ide/generator-theia-extension/wiki/Re-licensing-theia-ide-generator-theia-extension) under the `Eclipse Foundation` including re-licensing (https://github.com/theia-ide/generator-theia-extension/pull/73), it'd be better to have this completed first before accepting and merging the changes.

I will mark the pull-request as `changes requested` only to block the pull-request from being accidentally merged.

cc @marcdumais-work

**Comment by marcdumais-work** [comment]
@vince-fugnitto the new license is in effect. 

@kobzarvs Please be aware that this repository has [a new license](https://github.com/theia-ide/generator-theia-extension/blob/master/LICENSE). Please have a look and signal your acceptance of the new license, for this contribution, by rebasing it on our latest master and force-pushing to your PR branch. 

Let me know if you need help doing the above - I'm happy to assist.

**Comment by marcdumais-work** [comment]
cc: @JonasHelming

**Comment by vince-fugnitto** [comment]
Closed since it was fixed as part of #94.

**Pull request closed without merging**
