### PR TITLE
Template widget must handle focus

### LINKED ISSUE #145: Generated widget does not correctly accept focus
This leads to the following message:

 root WARN Widget was activated, but did not accept focus after 2000ms: getting.started.widget

see also: https://github.com/eclipse-theia/theia/issues/10878

### PR DESCRIPTION
**Pull request by JonasHelming**
fixed #145

Signed-off-by: Jonas Helming <jhelming@eclipsesource.com>

### CODE REVIEW

**Review by vince-fugnitto — COMMENTED** [review]
@JonasHelming the changes look good, but they do not take effect since we do not use `activate` when opening the view, see:

https://github.com/eclipse-theia/generator-theia-extension/blob/55fead2e28be2740295286898014101f49bf82b7/templates/widget/contribution.ts#L49

**Comment by JonasHelming** [comment]
Make sense, but without the fix, I get an error that the widgets was not activated. The first video is the template as is, the second with my fix. I believe this is a regression anyways, because I never experienced this issue in the template before and I use it quite frequently.

withoutfix
withfix

**Comment by vince-fugnitto** [comment]
@JonasHelming it does not seem to happen to me at least without the fix, I don't see any code at the moment that uses the `activate` request for the widget.

https://user-images.githubusercontent.com/40359487/167223985-e1ca2438-fdf2-4a3a-94c1-019cf90ba72d.mov

I did a fresh build, and am using the latest version of the generator. If you can reproduce with a fresh generation can you provide steps as to how you reproduced the warning.

**Comment by JonasHelming** [comment]
I am also on the latest version
I just:
-  generated the widget extension
- Start the browser app
- open the template widget (view => name of the widget)
- focus another view (e.g. the explorer)
- focus the template widget by clicking on the tab (either the icon in the site bar on the left stack or the tab when in the main stack, both leads to the same result
- observe the warning the the server console

@jfaltermeier Could you please restest this as well?

**Comment by jfaltermeier** [comment]
> I am also on the latest version I just:
> 
> * generated the widget extension
> * Start the browser app
> * open the template widget (view => name of the widget)
> * focus another view (e.g. the explorer)
> * focus the template widget by clicking on the tab (either the icon in the site bar on the left stack or the tab when in the main stack, both leads to the same result
> * observe the warning the the server console
> 
> @jfaltermeier Could you please restest this as well?

With those steps I can reproduce the issue when switching back to the view from the Explorer by clicking on the view's icon in the left tab bar. 
However when (re-)opening the view from the menu I did not get the warning (because the command uses `activate: false` I guess)

I've applied the proposed changes to the generated template view and this fixes the issue. 

Should we maybe change the command to use `activate: true` as well?

**Review by vince-fugnitto — APPROVED** [review]

**Pull request merged**
