### PR TITLE
bumped yeoman version to "^5.0.0", solves #182

### PR DESCRIPTION
**Pull request by sailingKieler**
* added launch config for debugging the generator
* tested with yo@4 and yo@5

@JonasHelming What do you think?

### CODE REVIEW

**Comment by JonasHelming** [comment]
Great! I will test once the build succeeds!

**Comment by sailingKieler** [comment]
🎉

🚀

**Comment by JonasHelming** [comment]
LGTM and works

**Review by JonasHelming — APPROVED** [review]

**Comment by JonasHelming** [comment]
@vince-fugnitto I believe this with https://github.com/eclipse-theia/generator-theia-extension/pull/184 would justify a new release

**Pull request merged**
